config/routes.rb
Rails.application.routes.default_url_options[:host] = Settings.application.canonical_hostname

Rails.application.routes.draw do
  devise_for :users, path: "auth", class_name: 'User', controllers: { registrations: "users/registrations" }

  resources :users do
    member do
      post :send_invitation
    end

    resources :user_roles, only: [:new, :create, :destroy], as: :roles
  end

  devise_scope :user do
    get '/sign_in' => 'devise/sessions#new'
    get '/sign_out' => 'devise/sessions#destroy'
    get '/sign_up' => 'devise/registrations#new'
  end


  resources :schools do
    collection do
      get :table
    end

    member do
      get :primary_contact_input
    end
  end

  resources :school_programs

  resources :community_programs do
    resources :build,
      only: [:show, :update],
      controller: 'community_programs/build'

    collection do
      get :table
    end

    member do
      put :merge
      put :toggle_active
    end
  end

  resources :organizations do
    collection do
      get :table
    end

    member do
      get :verification
      get :primary_contact_input
    end
  end

  resources :quality_elements do
    member do
      get :service_type_inputs
    end
  end

  resources :service_types

  resources :api do
    collection do
      get :community_programs
      get :school_hierarchy
      get :schools
      get :school_sub_areas
    end
  end

  scope 'api' do
    if Settings.application.public_view_enabled
      get 'config/school_map', to: 'api/configuration#school_map'
      get 'schools/map_markers/:site_type', to: 'api/schools#map_markers'
    end
  end

  resources :visualizations do
    collection do
      get :school_hierarchy
    end
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :public_authorizations, only: [:show] do
      collection do
        post :community_program
        post :organization
      end
    end
  end

  if Settings.application.public_view_enabled
    namespace :public do
      resources :schools, only: [:index, :show]
      resources :organizations, only: [:index, :show]
      resources :community_programs, only: [:show]
      resources :quality_elements, only: [:index, :show]
    end

    root to: "public/special#home"
  else
    root to: "schools#index"
  end
end

app/models/service_type.rb
class ServiceType < ApplicationRecord
  has_many :quality_element_service_types, dependent: :destroy
  has_many :quality_elements, through: :quality_element_service_types

  has_many :community_program_quality_element_service_types
  has_many :community_program_quality_elements,
    through: :community_program_quality_element_service_types

  validates :name, presence: true
  validates :quality_elements, presence: true

  def default_display
    self.name
  end

  def quality_element_groups
    @quality_element_groups ||= community_program_quality_elements.
      group_by(&:quality_element_id)
  end

  def community_programs_for_quality_element_service_type(quality_element)
    groups = quality_element_groups[quality_element.id]

    if groups
      groups.map{|g| g.community_program}
    else
      []
    end
  end

  def schools_for_quality_element_service_type(quality_element)
    community_programs_for_quality_element_service_type(quality_element).
      compact.map{|cp|
        cp.school_programs.map{|sp| sp.school}
      }.flatten.uniq
  end

  def organizations_for_quality_element_service_type(quality_element)
    community_programs_for_quality_element_service_type(quality_element).
      compact.map{|cp| cp.organization}.uniq
  end
end

app/controllers/service_types_controller.rb
class ServiceTypesController < ApplicationController
  def index
    @quality_elements = QualityElement.accessible_by(current_ability).includes(:service_types).order("service_types.name")
    authorize! :index, QualityElement
  end

  def show
    @service_type = ServiceType.find(params[:id])
    authorize! :show, @service_type
  end

  def new
    @service_type = ServiceType.new
    authorize! :new, @service_type
  end

  def create
    @service_type = ServiceType.new(service_type_params)
    authorize! :create, @service_type

    @service_type.save

    redirect_to service_type_path(@service_type)
  end

  def edit
    @service_type = ServiceType.find(params[:id])
    authorize! :edit, @service_type
  end

  def update
    @service_type = ServiceType.find(params[:id])
    authorize! :update, @service_type

    @service_type.update(service_type_params)

    redirect_to service_type_path(@service_type)
  end

  private

  def service_type_params
    params.
      require(:service_type).
      permit(
        :name,
        quality_element_ids: []
      )
  end

end

app/views/service_types/_form.html.erb
<%= f.input :name %>
<%= f.input :quality_element_ids,
  collection: QualityElement.accessible_by(current_ability).order(:name),
  label: t("quality_element.class.name"),
  input_html: { multiple: true } %>

<%= f.submit t('forms.buttons.save'),
  class: "btn btn-large btn-success" %>

app/views/service_types/edit.html.erb
<%= breadcrumb [
  ['Service Types', service_types_path],
  [truncate(@service_type.name, length: 20), service_type_path(@service_type)],
  ["Edit", ""]] %>

<div class="row-fluid">
  <div class="span12">
    <%= page_header("Edit '#{@service_type.name}'", "") %>

    <div class="form_wrapper">
      <%= simple_form_for @service_type, method: :put, html: {class: "form-horizontal"} do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>
      <% end %>
    </div>
  </div>
</div>

app/views/service_types/index.html.erb
<%= breadcrumb [['Service Types', service_types_path]] %>

<div class="row-fluid">
  <div class="span12">
    <%= page_header("Service Types", "") do %>
      <%= link_to 'Create New Service Type', new_service_type_path, class: "btn btn-primary" %>
    <% end %>

    <div class="table_wrapper">
      <table class="table table-striped table-hover table-sorter service_types">
        <thead>
          <tr>
            <th>Service Type</th>
            <th><%= I18n.t('quality_element.class.name') %></th>
            <th class="center">Schools</th>
            <th class="center">Organizations</th>
            <th class="center">Community Programs</th>
            <th class="actions buttons sorter-false filter-false"></th>
          </tr>
        </thead>

        <tbody>
          <% @quality_elements.each do |quality_element| %>
            <% quality_element.service_types.each do |service_type| %>
              <tr>
                <td><%= service_type.name %></td>
                <td><%= quality_element.name %></td>
                <td class="center"><%= service_type.schools_for_quality_element_service_type(quality_element).count %></td>
                <td class="center"><%= service_type.organizations_for_quality_element_service_type(quality_element).count %></td>
                <td class="center"><%= service_type.community_programs_for_quality_element_service_type(quality_element).count %></td>
                <td class="actions buttons center">
                  <%= link_to 'view',
                    service_type_path(service_type),
                    class: "btn btn-small btn-info" %>
                  <%= link_to 'edit',
                    edit_service_type_path(service_type),
                    class: "btn btn-small btn-primary" %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/service_types/new.html.erb
<%= breadcrumb [
  ['Service Types', service_types_path],
  ["Create", ""]
] %>

<div class="row-fluid">
  <div class="span12">
    <%= page_header("Create New Service Type", "") %>

    <div class="form_wrapper">
      <%= simple_form_for @service_type, method: :post, html: {class: "form-horizontal"} do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>
      <% end %>
    </div>
  </div>
</div>

app/views/service_types/show.html.erb
<%= breadcrumb [
  ['Service Types', service_types_path],
  [truncate(@service_type.name, length: 20), service_type_path(@service_type)]
] %>


<div class="row-fluid">
  <div class="span12">
    <%= page_header(@service_type.name, "") do %>
      <%= link_to 'Edit', edit_service_type_path(@service_type), class: "btn btn-primary" %>
    <% end %>

    <div class="table_wrapper">
     <table class="table table-striped">
        <thead>
          <tr>
            <th><%= I18n.t('quality_element.class.name') %></th>
            <th class="center">Schools</th>
            <th class="center">Organizations</th>
            <th class="center">Community Programs</th>
          </tr>
        </thead>

        <tbody>
          <% @service_type.quality_elements.sort_by(&:name).each do |quality_element| %>
            <tr>
              <td><%= link_to quality_element.name, quality_element_path(quality_element) %></td>
              <td class="center"><%= @service_type.schools_for_quality_element_service_type(quality_element).count %></td>
              <td class="center"><%= @service_type.organizations_for_quality_element_service_type(quality_element).count %></td>
              <td class="center"><%= @service_type.community_programs_for_quality_element_service_type(quality_element).count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>