config/routes.rb
Rails.application.routes.default_url_options[:host] = Settings.application.canonical_hostname

Rails.application.routes.draw do
  devise_for :users, path: "auth", class_name: 'User', controllers: { registrations: "users/registrations" }

  resources :users do
    member do
      post :send_invitation
    end

    resources :user_roles, only: [:new, :create, :destroy], as: :roles
  end

  devise_scope :user do
    get '/sign_in' => 'devise/sessions#new'
    get '/sign_out' => 'devise/sessions#destroy'
    get '/sign_up' => 'devise/registrations#new'
  end


  resources :schools do
    collection do
      get :table
    end

    member do
      get :primary_contact_input
    end
  end

  resources :school_programs

  resources :community_programs do
    resources :build,
      only: [:show, :update],
      controller: 'community_programs/build'

    collection do
      get :table
    end

    member do
      put :merge
      put :toggle_active
    end
  end

  resources :organizations do
    collection do
      get :table
    end

    member do
      get :verification
      get :primary_contact_input
    end
  end

  resources :quality_elements do
    member do
      get :service_type_inputs
    end
  end

  resources :service_types

  resources :api do
    collection do
      get :community_programs
      get :school_hierarchy
      get :schools
      get :school_sub_areas
    end
  end

  scope 'api' do
    if Settings.application.public_view_enabled
      get 'config/school_map', to: 'api/configuration#school_map'
      get 'schools/map_markers/:site_type', to: 'api/schools#map_markers'
    end
  end

  resources :visualizations do
    collection do
      get :school_hierarchy
    end
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :public_authorizations, only: [:show] do
      collection do
        post :community_program
        post :organization
      end
    end
  end

  if Settings.application.public_view_enabled
    namespace :public do
      resources :schools, only: [:index, :show]
      resources :organizations, only: [:index, :show]
      resources :community_programs, only: [:show]
      resources :quality_elements, only: [:index, :show]
    end

    root to: "public/special#home"
  else
    root to: "schools#index"
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController

  def index
    authorize! :view, :admin_dashboard
    @presenter = Admin::DashboardPresenter.new
  end

end

app/views/admin/dashboard/_community_program_status.html.erb
<div class="program-count-container">
  <dl>
    <dt>Publicly Viewable Community Programs</dt>
    <dd>
      <%= CommunityProgram.publicly_accessible.count %>
    </dd>
  </dl>
</div>

<div class="table_wrapper">
  <table class="table table-striped table-hover table-sorter admin-table community-program-status">
    <thead>
      <tr>
        <th class="programs">Program Name</th>
        <th class="last-updated">Program Last Changed</th>
        <th class="school-count">School Count</th>
        <th class="last-verfied">Verfied</th>
        <th class="with-progress-bar">Program Completion Rate</th>
        <th class="school-program-completion">School Programs with Differing Completion Rates</th>
      </tr>
    </thead>

    <tbody>
      <% community_programs.each do |community_program| %>
        <tr>
          <td>
            <%= link_to community_program.name, community_program_path(community_program) %>
          </td>
          <td>
            <%= community_program.updated_at %>
          </td>
          <td class="text-center">
            <%= community_program.school_programs.size %>
          </td>
          <td class="text-center">
            <%= boolean_checkmark_gicon(
              !community_program.verification_required?,
              {data: {tooltip: last_verified_tooltip(community_program)}}
            ) %>
          </td>
          <td>
            <%= ProgressBarPresenter.perform(
              percentage: community_program.completion_rate,
              options: {
                verification_required: community_program.verification_required?,
                tooltip: community_program.completion_rate_tooltip,
                tooltip_class: 'cj-cp-progress-tooltip'
              }
            ) %>
          </td>
          <td>
            <% if community_program.schools_with_differing_completion_rates.present? %>
              <%= view_more_toggle_list(
                    community_program.
                    decorate.
                    schools_with_differing_completion_rates
                  ) do |school_program|
                      "#{school_program.school.name} (#{number_to_percentage(school_program.completion_rate, precision: 0)})"
                    end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/dashboard/_organization_status.html.erb
<div class="program-count-container">
  <dl>
    <dt>All Organizations</dt>
    <dd>
      <%= Organization.count %>
      (<%= pluralize(Organization.with_community_programs.size, 'programs') %>)
    </dd>

    <dt>OUSD Organizations</dt>
    <dd>
      <%= Organization.ousd.count %>
      (<%= pluralize(Organization.ousd.with_community_programs.size, 'programs') %>)
    </dd>

    <dt>Non-OUSD Organizations</dt>
    <dd>
      <%= Organization.non_ousd.count %>
      (<%= pluralize(Organization.non_ousd.with_community_programs.size, 'programs') %>)
    </dd>

    <dt>Publicly Viewable Organizations</dt>
    <dd>
      <%= Organization.publicly_accessible.count %>
    </dd>
  </dl>
</div>

<div class="table_wrapper">
  <table class="table table-striped table-hover table-sorter admin-table organization-status">
    <thead>
      <tr>
        <th class="organizations">Organization</th>
        <th class="last-updated">Most Recent User Logged In</th>
        <th class="last-verfied">Verfied</th>
        <th class="orientation-attended">Orientation Attended?</th>
        <th class="program-count">Program Count</th>
        <th class="with-progress-bar">Organization Data Completion</th>
        <th class="with-progress-bar">Average Program Data Completion</th>
      </tr>
    </thead>

    <tbody>
      <% organizations.each do |organization| %>
        <tr>
          <td>
            <%= link_to organization.name, organization_path(organization) %>
          </td>
          <td>
            <%= organization.last_sign_in %>
          </td>
          <td class="text-center">
            <%= boolean_checkmark_gicon(
              !organization.verification_required?,
              {data: {tooltip: last_verified_tooltip(organization)}}
            ) %>
          </td>
          <td class="text-center">
            <%= boolean_checkmark_gicon(
              organization.any_users_attended_orientation?,
              {data: {tooltip: organization.last_orientation_attended_tooltip}}
            ) %>
          </td>
          <td class="text-center">
            <%= organization.community_programs.size %>
          </td>
          <td>
            <%= ProgressBarPresenter.perform(
              percentage: organization.completion_rate,
              options: {
                verification_required: organization.verification_required?,
                tooltip: organization.completion_rate_tooltip,
                tooltip_class: 'cj-org-progress-tooltip'
              }
            ) %>
          </td>
          <td>
            <% if organization.community_programs.present? %>
              <%= ProgressBarPresenter.perform(
                percentage: organization.average_program_completion_rate,
                options: {
                  verification_required: organization.unverified_program_count > 0
                }
              ) %>
            <% else %>
              NA
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/dashboard/_page_views.html.erb
<div class="table_wrapper">
  <table class="table table-striped table-hover table-sorter">
    <thead>
      <tr>
        <th>User ID</th>
        <th>Email</th>
        <th>Url</th>
        <th>Completed In</th>
        <th>Time</th>
        <th>Status</th>
        <th>XHR</th>
        <th>User Agent</th>
        <th>Controller</th>
        <th>Action</th>
        <th>ID Param</th>
        <th>PID</th>
      </tr>
    </thead>

    <tbody>
      <% records.each do |record| %>
        <tr>
          <td><%= record.user_id %></td>
          <td><%= record.user.email %></td>
          <td><%= record.url %></td>
          <td><%= record.completed_in %></td>
          <td><%= record.created_at.to_s(:datetime_with_seconds) %></td>
          <td><%= record.status %></td>
          <td><%= record.xhr? %></td>
          <td><%= record.user_agent %></td>
          <td><%= record.controller %></td>
          <td><%= record.action %></td>
          <td><%= record.id_parameter %></td>
          <td><%= record.pid %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/dashboard/_public_authorizations.html.erb
<div class="table_wrapper">
  <table class="table table-striped table-hover table-sorter admin-table public-authorizations">
    <thead>
      <tr>
        <th class="organizations">Organization</th>
        <th class="status filter-select filter-exact" data-placeholder="All">Public</th>
        <th class="eligible filter-select filter-exact" data-placeholder="All">Eligible</th>
        <th class="programs-eligible filter-select filter-exact" data-placeholder="All">Eligible Programs</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% organizations.each do |organization| %>
        <tr>
          <td>
            <%= link_to organization.name, organization_path(organization) %>
          </td>
          <td class="text-center">
            <%= boolean_checkmark_gicon(
              organization.approved_for_public?,
              data: {sort_value: t("admin.public_bool.#{organization.approved_for_public?}")}
            ) %>
          </td>
          <td class="text-center">
            <%= boolean_checkmark_gicon(
              organization.can_be_made_public?,
              data: {sort_value: t("admin.eligible_bool.#{organization.can_be_made_public?}")}
            ) unless organization.approved_for_public? %>
          </td>
          <td class="text-center">
            <%= boolean_checkmark_gicon(
              organization.eligible_programs.count > 0,
              data: {sort_value: t("admin.eligible_bool.#{organization.eligible_programs.count > 0}")}
            ) unless organization.community_programs.active.all?{|cp| cp.approved_for_public?} %>
          </td>
          <td class="text-center">
            <%= link_to_gicon('manage',
              admin_public_authorization_path(organization),
              class: "btn btn-small btn-primary",
              icon: 'wrench') %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/dashboard/index.html.erb
<%= breadcrumb [['Dashboard', '']] %>

<div class="row-fluid">
  <div class="span12">
    <%= page_header("Admin Dashboard", "") %>

    <%= page_nav_tabs @presenter.nav_tabs %>

    <div class="tab-content">
      <% if can? :view, :super_admin_dashboard_items %>
        <div id="page-views" class="tab-pane active">
          <%= render partial: 'page_views', locals: {records: @presenter.page_views} %>
        </div>

        <div id="api-hits" class="tab-pane active">
          <%= render partial: 'page_views', locals: {records: @presenter.api_hits} %>
        </div>

        <div id="analytics" class="tab-pane">
          <%#= render partial: 'analytics', locals: {analytics: @analytics} %>
        </div>
      <% end %>

      <% if can? :manage, Organization %>
        <div id="organization-status" class="tab-pane">
          <%= render partial: 'organization_status', locals: {
            organizations: @presenter.organizations
          } %>
        </div>
      <% end %>

      <% if can? :manage, CommunityProgram %>
        <div id="community-program-status" class="tab-pane">
          <%= render partial: 'community_program_status', locals: {
            community_programs: @presenter.community_programs
          } %>
        </div>
      <% end %>

      <% if can? :manage, :public_authorizations %>
        <div id="public-authorizations" class="tab-pane">
          <%= render partial: 'public_authorizations', locals: {
            organizations: @presenter.organizations
          } %>
        </div>
      <% end %>
    </div>
  </div>
</div>