config/routes.rb
Rails.application.routes.default_url_options[:host] = Settings.application.canonical_hostname

Rails.application.routes.draw do
  devise_for :users, path: "auth", class_name: 'User', controllers: { registrations: "users/registrations" }

  resources :users do
    member do
      post :send_invitation
    end

    resources :user_roles, only: [:new, :create, :destroy], as: :roles
  end

  devise_scope :user do
    get '/sign_in' => 'devise/sessions#new'
    get '/sign_out' => 'devise/sessions#destroy'
    get '/sign_up' => 'devise/registrations#new'
  end


  resources :schools do
    collection do
      get :table
    end

    member do
      get :primary_contact_input
    end
  end

  resources :school_programs

  resources :community_programs do
    resources :build,
      only: [:show, :update],
      controller: 'community_programs/build'

    collection do
      get :table
    end

    member do
      put :merge
      put :toggle_active
    end
  end

  resources :organizations do
    collection do
      get :table
    end

    member do
      get :verification
      get :primary_contact_input
    end
  end

  resources :quality_elements do
    member do
      get :service_type_inputs
    end
  end

  resources :service_types

  resources :api do
    collection do
      get :community_programs
      get :school_hierarchy
      get :schools
      get :school_sub_areas
    end
  end

  scope 'api' do
    if Settings.application.public_view_enabled
      get 'config/school_map', to: 'api/configuration#school_map'
      get 'schools/map_markers/:site_type', to: 'api/schools#map_markers'
    end
  end

  resources :visualizations do
    collection do
      get :school_hierarchy
    end
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :public_authorizations, only: [:show] do
      collection do
        post :community_program
        post :organization
      end
    end
  end

  if Settings.application.public_view_enabled
    namespace :public do
      resources :schools, only: [:index, :show]
      resources :organizations, only: [:index, :show]
      resources :community_programs, only: [:show]
      resources :quality_elements, only: [:index, :show]
    end

    root to: "public/special#home"
  else
    root to: "schools#index"
  end
end

app/models/quality_element.rb
class QualityElement < ApplicationRecord
  has_many :quality_element_service_types
  has_many :service_types, through: :quality_element_service_types

  has_many :community_program_quality_elements
  has_many :community_programs, through: :community_program_quality_elements

  has_many :school_programs, through: :community_programs

  has_many :schools, through: :community_programs
  has_many :organizations, through: :community_programs

  validates :name, presence: true
  validates :element_type, presence: true,
    inclusion: {in: Proc.new { QualityElement.element_types }}

  scope :cte, -> { where(element_type: 'cte') }
  scope :foundational, -> { where(element_type: 'foundational') }
  scope :programmatic, -> { where(element_type: 'programmatic') }

  # only return quality elements that have service types
  scope :with_service_types, -> {
    joins(:quality_element_service_types).
    where.not(quality_element_service_types: {service_types: nil}).
    uniq
  }

  before_create :generate_identifier

  scope :publicly_accessible, -> {
    where("1=1")
  }

  def default_display
    self.name
  end

  def foundational?
    element_type == 'foundational'
  end

  def programmatic?
    element_type == 'programmatic'
  end

  def identifier
    self['identifier'].to_sym
  end

  def description
    I18n.t("quality_elements.descriptions.#{identifier}") || ""
  end

  def self.element_types
    %w(programmatic foundational)
  end

  private

  def generate_identifier
    self.identifier = self.name.downcase.gsub(/[^\w]+/, "_").gsub(/_\z/, '')
  end
end

app/controllers/quality_elements_controller.rb
class QualityElementsController < ApplicationController

  def index
    @quality_elements = QualityElement.accessible_by(current_ability).order(:name)
    authorize! :read, QualityElement
  end

  def show
    @quality_element = QualityElement.accessible_by(current_ability).find(params[:id])
    authorize! :read, @quality_element
  end

  def new
    @quality_element = QualityElement.new
    authorize! :create, @quality_element
  end

  def create
    @quality_element = QualityElement.new(quality_element_params)
    authorize! :create, @quality_element

    @quality_element.save

    redirect_to quality_element_path(@quality_element)
  end

  def edit
    @quality_element = QualityElement.find(params[:id])
    authorize! :edit, @quality_element
  end

  def update
    @quality_element = QualityElement.find(params[:id])
    authorize! :edit, @quality_element

    @quality_element.update(quality_element_params)

    redirect_to quality_element_path(@quality_element)
  end

  def service_type_inputs
    @quality_element = QualityElement.accessible_by(current_ability).
      includes(:service_types).find(params[:id])
    authorize! :read, @quality_element

    render "/community_programs/service_type_inputs", locals: {
      element_type: params[:type]
    }, layout: false
  end

  private

  def quality_element_params
    params.require(:quality_element).permit(:name, :element_type)
  end
end

app/helpers/quality_elements_helper.rb
module QualityElementsHelper
  def quality_elements_coverage_display(quality_element_count)
    sub_area_count = QualityElement.
      programmatic.
      accessible_by(current_ability).
      count

    ratio = quality_element_count.to_f / sub_area_count.to_f

    display_class = ratio > 0.7 ? 'good' : (ratio > 0.5 ? 'satisfactory' : 'bad')

    content_tag(:span, class: display_class) do
      concat "#{quality_element_count}/#{sub_area_count}"
      concat content_tag(:span, '', class: 'status-circle' )
    end
  end

  def community_program_count_for_element(quality_element, school)
    count = school.community_programs.
      includes(:quality_element).
      reject{|cp| cp.quality_element.nil?}.
      select{|cp| cp.quality_element.id == quality_element.id}
      .count

    content_tag(:span, count, class: count > 0 ? 'satisfactory' : 'bad')
  end
end

app/views/quality_elements/_form.html.erb
<%= f.input :name %>
<%= f.input :element_type, as: :select,
  collection: QualityElement.element_types.map{|t| [t,t]} %>

<%= f.submit 'Save',
  class: "btn btn-large btn-success" %>

app/views/quality_elements/edit.html.erb
<%= breadcrumb [
  [I18n.t('quality_element.class.name').pluralize, quality_elements_path],
  [truncate(@quality_element.name, length: 20), quality_element_path(@quality_element)],
  ["Edit", ""]
] %>

<div class="row-fluid">
  <div class="span12">
    <%= page_header("Edit '#{@quality_element.name}'", "") %>

    <div class="form_wrapper">
      <%= simple_form_for @quality_element, method: :put, html: {class: "form-horizontal"} do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>
      <% end %>
    </div>
  </div>
</div>

app/views/quality_elements/index.html.erb
<%= breadcrumb [[I18n.t('quality_element.class.name').pluralize, quality_elements_path]] %>

<div class="row-fluid">
  <div class="span12">
    <%= page_header(I18n.t('quality_element.class.name').pluralize, "") do %>
      <%= link_to("Create New #{I18n.t('quality_element.class.name')}",
        new_quality_element_path,
        class: "btn btn-primary") if can?(:create, QualityElement) %>
    <% end %>

    <div class="table_wrapper">
      <table class="table table-striped table-hover table-sorter quality_elements">
        <thead>
          <tr>
            <th><%= I18n.t('quality_element.class.name') %></th>
            <th>Element Type</th>
            <th>Schools</th>
            <th>Organizations</th>
            <th class="actions sorter-false filter-false"></th>
          </tr>
        </thead>

        <tbody>
          <% @quality_elements.each do |element| %>
            <tr>
              <td><%= element.name %></td>
              <td><%= element.element_type %></td>
              <td><%= element.schools.count %></td>
              <td><%= element.organizations.count %></td>
              <td class="actions center">
                <%= link_to 'view',
                  quality_element_path(element),
                  class: "btn btn-small btn-info" %>
                <%= link_to('edit',
                  edit_quality_element_path(element),
                  class: "btn btn-small btn-primary") if can?(:edit, QualityElement) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/quality_elements/new.html.erb
<%= breadcrumb [
  [I18n.t('quality_element.class.name').pluralize, quality_elements_path],
  ["Create", ""]
] %>

<div class="row-fluid">
  <div class="span12">
    <%= page_header("Create New #{I18n.t('quality_element.class.name')}", "") %>

    <div class="form_wrapper">
      <%= simple_form_for @quality_element, method: :post, html: {class: "form-horizontal"} do |f| %>
        <%= render :partial => 'form', :locals => {:f => f} %>
      <% end %>
    </div>
  </div>
</div>

app/views/quality_elements/show.html.erb
<%= breadcrumb [
  [I18n.t('quality_element.class.name').pluralize, quality_elements_path],
  [truncate(@quality_element.name, length: 20), quality_element_path(@quality_element)]
] %>

<div class="row-fluid">
  <div class="span12">
    <%= page_header(@quality_element.name, "") do %>
      <%= link_to('Edit',
        edit_quality_element_path(@quality_element),
        class: "btn btn-primary") if can?(:edit, QualityElement) %>
    <% end %>

    <div class="table_wrapper">
     <table class="table table-striped">
        <thead>
          <tr>
            <th>Schools</th>
            <th>Partner Organizations</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td><%= @quality_element.schools.uniq.count %></td>
            <td><%= @quality_element.organizations.uniq.count %></td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="table_wrapper">
      <% @quality_element.school_programs.group_by(&:school).each do |school, school_programs| %>
        <% next unless school %>

        <h2><%= link_to school.try(:name), school_path(school) %></h2>

        <table class="table table-striped">
          <thead>
            <tr>
              <th>Partner Organization</th>
              <th><%= I18n.t('quality_element.class.name') %></th>
              <th>Service Types</th>
            </tr>
          </thead>

          <tbody>
            <% school_programs.each do |school_program| %>
              <tr>
                <td><%= link_to school_program.organization.try(:name), community_program_path(school_program.community_program) %></td>
                <td><%= school_program.quality_element.try(:name) %></td>
                <td><%= school_program.service_types.map{|st| st.name}.join(', <br />').html_safe %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>